
export const PHASES = {
  TYPE_OF_SPACE: 'TYPE_OF_SPACE',
  QUESTIONNAIRE: 'QUESTIONNAIRE',
  MORE_DETAILS: 'MORE_DETAILS',
  DESIGN_IMAGES: 'DESIGN_IMAGES',
  USER_IMAGE_UPLOAD: 'USER_IMAGE_UPLOAD',
  SPACE_DESCRIPTION: 'SPACE_DESCRIPTION',
};

export const MESSAGE_TYPES = {
  QUESTIONNAIRE: 'QUESTIONNAIRE',
  DESIGN_IMAGES: 'DESIGN_IMAGES',
  USER_IMAGE_UPLOAD: 'USER_IMAGE_UPLOAD',
  SPACE_DESCRIPTION: 'SPACE_DESCRIPTION',
};
